<?php


namespace Firesphere\SolrManager\Admins;


use SilverStripe\Admin\LeftAndMain;
use SilverStripe\Security\PermissionProvider;

class SolrManager extends LeftAndMain implements PermissionProvider
{
    /**
     * @var int No need to sit up high in the menu
     */
    private static $menu_priority = 8;

    /**
     * @var string Give this a fancy name
     */
    private static $menu_title = 'Solr Manager';

    /**
     * @var string Where to find me
     */
    private static $url_segment = 'solr-manager';

    /**
     * @var string Add a pretty magnifying glass to the sidebar menu
     */
    private static $menu_icon_class = 'font-icon-search';

    public function providePermissions()
    {
        return parent::providePermissions(); // TODO: Change the autogenerated stub
    }
}
